# Generated by Django 3.2.10 on 2022-01-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('easy', 'Легкий'), ('normal', 'Нормальный'), ('hard', 'Сложный')], max_length=10, verbose_name='уровень сложности')),
                ('problem', models.TextField(verbose_name='условие задачи')),
                ('short_name', models.CharField(max_length=70, verbose_name='short_name')),
                ('contest_id', models.PositiveSmallIntegerField(default=9, verbose_name='contest_id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'db_table': 'problems',
            },
        ),
    ]
