# Generated by Django 3.2.10 on 2022-01-19 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_id', models.PositiveSmallIntegerField(verbose_name='judge_id')),
                ('code', models.TextField(verbose_name='решение задачи')),
                ('lang', models.CharField(choices=[('python3', 'Python 3'), ('g++', 'C++')], max_length=15, verbose_name='язык программирования')),
                ('result', models.CharField(blank=True, editable=False, max_length=10, null=True, verbose_name='результат проверки')),
                ('test_count', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='количество успешных тестов')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battle.problem', verbose_name='пользователь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'попытка',
                'verbose_name_plural': 'попытки',
                'db_table': 'solutions',
                'ordering': ('-modified',),
            },
        ),
    ]
