# Generated by Django 3.2.10 on 2022-01-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='judge_id',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='judge_id'),
        ),
    ]
